# Generated by Django 2.2.4 on 2019-10-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='typeRel',
            field=models.CharField(blank=True, choices=[('разработка', 'разработка'), ('экспертиза', 'экспертиза'), ('аукцион', 'аукцион'), ('строительство', 'строительство'), ('сдача', 'сдача'), ('выплата', 'выплата'), ('завершен', 'завершен')], max_length=24, verbose_name='тип'),
        ),
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
