# Generated by Django 2.2 on 2019-11-04 09:43

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='news_avatars/no_news.jpg', upload_to='news_avatars', verbose_name='картинка новости'),
        ),
    ]
