# Generated by Django 2.2.4 on 2019-11-03 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newshastechnicalsolutions',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='newshastechnicalsolutions',
            name='value',
        ),
        migrations.CreateModel(
            name='NewsDiscussMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('News', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.News', verbose_name='новость обсуждения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='участник обсуждения')),
            ],
        ),
        migrations.CreateModel(
            name='NewsDiscussItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=1500, null=True, verbose_name='добавить сообщение')),
                ('News', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.News', verbose_name='новость обсуждения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='участник обсуждения')),
            ],
        ),
    ]
