# Generated by Django 2.2.4 on 2019-10-29 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0001_initial'),
        ('newsapp', '0002_auto_20191028_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='typeRel',
        ),
        migrations.CreateModel(
            name='NewsHasTechnicalSolutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='название конструкции или участка')),
                ('value', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Объем работ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='newsapp.News', verbose_name='Новость')),
                ('techsol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='productsapp.TechnicalSolutions', verbose_name='Техническое решение')),
            ],
            options={
                'verbose_name': 'Тех решение проекта',
                'verbose_name_plural': 'Тех решения проекта',
            },
        ),
    ]
