# Generated by Django 2.2.4 on 2019-11-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20191103_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsdiscussitem',
            old_name='News',
            new_name='news',
        ),
        migrations.RenameField(
            model_name='newsdiscussmember',
            old_name='News',
            new_name='news',
        ),
    ]
