# Generated by Django 2.2.4 on 2019-11-05 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_auto_20191104_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdiscussitem',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='создан'),
            preserve_default=False,
        ),
    ]
