# Generated by Django 2.2 on 2019-10-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0007_technicalsolutions_short_desc'),
        ('projectsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='orderer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='techDes',
        ),
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='подрядчик'),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='заказчик'),
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='долгота'),
        ),
        migrations.AddField(
            model_name='project',
            name='technical_solutions',
            field=models.ManyToManyField(to='productsapp.TechnicalSolutions'),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='project',
            name='designer',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='проектировщик'),
        ),
        migrations.AlterField(
            model_name='project',
            name='finishDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
