# Generated by Django 2.2 on 2019-10-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='projects_images/1.jpg', upload_to='аватарка'),
        ),
    ]
