# Generated by Django 2.2.4 on 2019-10-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='project',
            name='longitude',
        ),
        migrations.AddField(
            model_name='project',
            name='coordinate',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='координаты'),
        ),
        migrations.AddField(
            model_name='project',
            name='map_mark',
            field=models.SlugField(blank=True, max_length=128, verbose_name='id метки на карте'),
        ),
        migrations.AddField(
            model_name='project',
            name='text_for_map',
            field=models.TextField(blank=True, max_length=240, null=True, verbose_name='текст для метки'),
        ),
    ]
