# Generated by Django 2.2 on 2019-10-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthastechnicalsolutions',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True, verbose_name='значение'),
        ),
    ]
