# Generated by Django 2.2 on 2019-10-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='заказчик'),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='заказчик'),
        ),
        migrations.AddField(
            model_name='project',
            name='designer',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='заказчик'),
        ),
    ]
