# Generated by Django 2.2 on 2019-10-31 19:30

from django.db import migrations
import imagekit.models.fields
import projectsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=projectsapp.models.image_upload_to),
        ),
    ]
