# Generated by Django 2.2.4 on 2019-11-03 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='projects_images/avatars'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('разработка', 'разработка'), ('экспертиза', 'экспертиза'), ('аукцион', 'аукцион'), ('строительство', 'строительство'), ('сдача', 'сдача'), ('выплата', 'выплата'), ('завершен', 'завершен')], max_length=24, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='projectcompany',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authapp.Company', verbose_name='Выберите компанию'),
        ),
        migrations.AlterField(
            model_name='projectcompany',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='projectsapp.Project'),
        ),
        migrations.AlterField(
            model_name='projectcompany',
            name='role',
            field=models.CharField(choices=[('проектировщик', 'проектировщик'), ('подрядчик', 'подрядчик'), ('заказчик', 'заказчик'), ('инспектор', 'инспектор'), ('технический заказчик', 'технический заказчик'), ('авторский надзор', 'авторский надзор'), ('агент', 'агент'), ('партнер', 'партнер')], max_length=24, verbose_name='роль в проекте'),
        ),
        migrations.AlterField(
            model_name='projectmanagers',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='projectmanagers',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='projectsapp.Project', verbose_name='проект'),
        ),
    ]
