# Generated by Django 2.2 on 2019-10-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0001_initial'),
        ('authapp', '0001_initial'),
        ('projectsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='designer',
        ),
        migrations.AddField(
            model_name='project',
            name='participant',
            field=models.ManyToManyField(to='authapp.Companies'),
        ),
        migrations.AddField(
            model_name='project',
            name='techsol',
            field=models.ManyToManyField(through='projectsapp.ProjectHasTechnicalSolutions', to='productsapp.TechnicalSolutions'),
        ),
    ]
