# Generated by Django 2.2 on 2019-10-02 08:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='finishDate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='orderer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='techDes',
        ),
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='город'),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='подрядчик'),
        ),
        migrations.AddField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='заказчик'),
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='долгота'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=128, unique=True, verbose_name='слаг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('разработка', 'разработка'), ('экспертиза', 'экспертиза'), ('аукцион', 'аукцион'), ('строительство', 'строительство'), ('сдача', 'сдача'), ('выплата', 'выплата'), ('завершен', 'завершен')], max_length=24, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='project',
            name='designer',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='проектировщик'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_desc', models.CharField(blank=True, max_length=128, verbose_name='alt фотографии')),
                ('image', models.ImageField(blank=True, upload_to='products_images', verbose_name='Фотография')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectsapp.Project')),
            ],
            options={
                'verbose_name': 'Фотография проекта',
                'verbose_name_plural': 'Фотографии проектов',
            },
        ),
        migrations.CreateModel(
            name='ProjectHasTechnicalSolutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True, verbose_name='широта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tech_sol', models.ManyToManyField(to='projectsapp.Project')),
            ],
        ),
    ]
