# Generated by Django 2.2 on 2019-10-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0002_auto_20191030_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='projects_images/avatars/no_avatar.jpg', upload_to='projects_images', verbose_name='Аватарка размером 1 х 1 !!!'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects_images', verbose_name='Фотография'),
        ),
    ]
