# Generated by Django 2.2 on 2019-11-02 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0002_auto_20191102_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanagers',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
