# Generated by Django 2.2 on 2019-10-22 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0002_projectdiscussitem_projectdiscussmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdiscussitem',
            name='comment',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='добавить сообщение'),
        ),
        migrations.AlterField(
            model_name='projectdiscussitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='участник обсуждения'),
        ),
        migrations.AlterField(
            model_name='projectdiscussmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='участник обсуждения'),
        ),
    ]
