# Generated by Django 2.2 on 2019-10-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0002_auto_20191002_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthastechnicalsolutions',
            name='project',
            field=models.ManyToManyField(to='projectsapp.Project'),
        ),
        migrations.AlterField(
            model_name='projecthastechnicalsolutions',
            name='tech_sol',
            field=models.ManyToManyField(to='productsapp.TechnicalSolutions'),
        ),
    ]
