# Generated by Django 2.2.4 on 2019-10-01 20:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0002_auto_20191001_0754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=128, unique=True, verbose_name='слаг'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_desc', models.CharField(blank=True, max_length=128, verbose_name='alt фотографии')),
                ('image', models.ImageField(blank=True, upload_to='products_images', verbose_name='Фотография')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectsapp.Project')),
            ],
            options={
                'verbose_name': 'Фотография проекта',
                'verbose_name_plural': 'Фотографии проектов',
            },
        ),
    ]
