# Generated by Django 2.2 on 2019-10-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0002_auto_20191006_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='participant',
            field=models.ManyToManyField(blank=True, to='authapp.Companies'),
        ),
    ]
