# Generated by Django 2.2 on 2019-10-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0002_auto_20191009_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='designer',
        ),
    ]
