# Generated by Django 2.2 on 2019-11-02 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0003_auto_20191102_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcompany',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authapp.Company', verbose_name='Выберите компанию'),
        ),
        migrations.AlterField(
            model_name='projectcompany',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='projectsapp.Project'),
        ),
        migrations.AlterField(
            model_name='projectcompany',
            name='role',
            field=models.CharField(choices=[('проектировщик', 'проектировщик'), ('подрядчик', 'подрядчик'), ('заказчик', 'заказчик'), ('инспектор', 'инспектор'), ('технический заказчик', 'технический заказчик'), ('авторский надзор', 'авторский надзор'), ('агент', 'агент'), ('партнер', 'партнер')], max_length=24, verbose_name='роль в проекте'),
        ),
    ]
