# Generated by Django 2.2 on 2019-10-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0003_auto_20191030_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects_images/avatars', verbose_name='Аватарка размером 1 х 1 !!!'),
        ),
    ]
