# Generated by Django 2.2 on 2019-10-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0003_auto_20191002_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='material',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='projecthastechnicalsolutions',
            name='value',
            field=models.FloatField(null=True, verbose_name='значение'),
        ),
    ]
