# Generated by Django 2.2 on 2019-11-02 17:05

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0004_auto_20191102_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='projects_images/avatars'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('разработка', 'разработка'), ('экспертиза', 'экспертиза'), ('аукцион', 'аукцион'), ('строительство', 'строительство'), ('сдача', 'сдача'), ('выплата', 'выплата'), ('завершен', 'завершен')], max_length=24, verbose_name='статус'),
        ),
    ]
