# Generated by Django 2.2 on 2019-10-20 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0004_auto_20191018_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanagers',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='projectmanagers',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='projectsapp.Project', verbose_name='проект'),
        ),
        migrations.AlterField(
            model_name='projectmanagers',
            name='role',
            field=models.CharField(choices=[('проектировщик', 'проектировщик'), ('подрядчик', 'подрядчик'), ('заказчик', 'заказчик'), ('инспектор', 'инспектор'), ('технический надзор', 'технический надзор'), ('авторский надзор', 'авторский надзор'), ('агент', 'агент'), ('партнер', 'партнер'), ('владелец', 'владелец'), ('коммерсант', 'коммерсант'), ('ассистент', 'ассистент')], max_length=24, verbose_name='роль в проекте'),
        ),
    ]
