# Generated by Django 2.2 on 2019-10-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0007_technicalsolutions_short_desc'),
        ('projectsapp', '0004_auto_20191002_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_sol',
            field=models.ManyToManyField(to='productsapp.TechnicalSolutions'),
        ),
        migrations.AddField(
            model_name='project',
            name='value',
            field=models.FloatField(null=True, verbose_name='значение'),
        ),
        migrations.DeleteModel(
            name='ProjectHasTechnicalSolutions',
        ),
    ]
