# Generated by Django 2.2 on 2019-10-11 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0004_auto_20191011_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthastechnicalsolutions',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='projectsapp.Project'),
        ),
    ]
