# Generated by Django 2.2 on 2019-10-02 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0007_technicalsolutions_short_desc'),
        ('projectsapp', '0005_auto_20191002_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tech_sol',
        ),
        migrations.RemoveField(
            model_name='project',
            name='value',
        ),
        migrations.CreateModel(
            name='ProjectHasTechnicalSolutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True, verbose_name='значение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectsapp.Project')),
                ('tech_sol', models.ManyToManyField(to='productsapp.TechnicalSolutions')),
            ],
        ),
    ]
