# Generated by Django 2.2 on 2019-10-30 13:46

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0005_auto_20191030_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='project_images/avatars'),
        ),
    ]
