# Generated by Django 2.2 on 2019-10-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0006_auto_20191002_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecthastechnicalsolutions',
            name='tech_sol',
        ),
    ]
