# Generated by Django 2.2 on 2019-10-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0007_technicalsolutions_short_desc'),
        ('projectsapp', '0007_remove_projecthastechnicalsolutions_tech_sol'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthastechnicalsolutions',
            name='tech_sol',
            field=models.ManyToManyField(to='productsapp.TechnicalSolutions'),
        ),
    ]
