# Generated by Django 2.2 on 2019-10-11 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectsapp', '0008_auto_20191011_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-updated',), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ManyToManyField(default=1, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
