# Generated by Django 2.2 on 2019-10-02 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0008_projecthastechnicalsolutions_tech_sol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecthastechnicalsolutions',
            options={'verbose_name': 'Тех решение проекта', 'verbose_name_plural': 'Тех решения проекта'},
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projectsapp.Project'),
        ),
    ]
