# Generated by Django 2.2 on 2019-10-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0009_auto_20191002_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecthastechnicalsolutions',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='projecthastechnicalsolutions',
            name='tech_sol',
            field=models.ManyToManyField(related_name='solutions', to='productsapp.TechnicalSolutions'),
        ),
    ]
