# Generated by Django 2.2 on 2019-10-03 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0007_technicalsolutions_short_desc'),
        ('projectsapp', '0011_auto_20191002_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecthastechnicalsolutions',
            name='tech_sol',
        ),
        migrations.AddField(
            model_name='projecthastechnicalsolutions',
            name='tech_sol',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='productsapp.TechnicalSolutions'),
        ),
    ]
