# Generated by Django 2.2 on 2019-10-03 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsapp', '0012_auto_20191003_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecthastechnicalsolutions',
            old_name='tech_sol',
            new_name='techsol',
        ),
    ]
