# Generated by Django 2.2.4 on 2019-09-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactApplication',
        ),
    ]
