# Generated by Django 2.2.4 on 2019-09-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0003_auto_20190929_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactapplication',
            options={'verbose_name': 'Форма обратной связи', 'verbose_name_plural': 'Формы обратной связи'},
        ),
    ]
