python manage.py loaddata authapp_db.json
python manage.py loaddata contactapp_db.json
python manage.py loaddata newaspp_db.json
python manage.py loaddata newsapp_db.json
python manage.py loaddata ordersapp_db.json
python manage.py loaddata partnersapp_db.json
python manage.py loaddata productsapp_db.json
python manage.py loaddata projectsapp_db.json
python manage.py loaddata researchapp_db.json
python manage.py loaddata servicesapp_db.json
python manage.py loaddata ymapapp_db.json