# Generated by Django 2.2 on 2019-10-04 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productsapp', '0007_technicalsolutions_short_desc'),
        ('authapp', '0002_categorycompany_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='название исследования')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, verbose_name='описание материала')),
                ('researcher', models.ManyToManyField(to='authapp.Company')),
                ('scientist', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Исследование',
                'verbose_name_plural': 'Исследования',
            },
        ),
        migrations.CreateModel(
            name='SubjectOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=28, unique=True, verbose_name='предмет исследования')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Исследование',
                'verbose_name_plural': 'Исследования',
            },
        ),
        migrations.CreateModel(
            name='ResearchFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_desc', models.CharField(blank=True, max_length=128, verbose_name='alt файла')),
                ('file', models.ImageField(blank=True, upload_to='research_files', verbose_name='файл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='researchapp.Research')),
            ],
            options={
                'verbose_name': 'Документ исследования',
                'verbose_name_plural': 'Документы исследования',
            },
        ),
        migrations.AddField(
            model_name='research',
            name='subject',
            field=models.ManyToManyField(to='researchapp.SubjectOfStudy'),
        ),
        migrations.AddField(
            model_name='research',
            name='techsol',
            field=models.ManyToManyField(to='productsapp.TechnicalSolutions'),
        ),
    ]
