# Generated by Django 2.2.4 on 2019-10-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='techsol',
            field=models.ManyToManyField(related_name='docs', to='productsapp.TechnicalSolutions', verbose_name='техническое решение'),
        ),
    ]
