# Generated by Django 2.2 on 2019-10-04 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_categorycompany_company'),
        ('productsapp', '0007_technicalsolutions_short_desc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('researchapp', '0002_auto_20191004_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='название категории')),
                ('comment', models.TextField(blank=True, verbose_name='комментарии')),
            ],
            options={
                'verbose_name': 'Категория документа',
                'verbose_name_plural': 'Категория документов',
            },
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name': 'Исследовательская работа', 'verbose_name_plural': 'Исследовательские работы'},
        ),
        migrations.AlterModelOptions(
            name='subjectofstudy',
            options={'verbose_name': 'Предмет исследование', 'verbose_name_plural': 'Предметы исследований'},
        ),
        migrations.AddField(
            model_name='research',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='research',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='researchfile',
            name='alt_desc',
            field=models.CharField(blank=True, max_length=128, verbose_name='название файла'),
        ),
        migrations.AlterField(
            model_name='subjectofstudy',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='предмет исследования'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='название документа')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
                ('company', models.ManyToManyField(blank=True, null=True, to='authapp.Company')),
                ('subject', models.ManyToManyField(blank=True, null=True, to='researchapp.SubjectOfStudy')),
                ('techsol', models.ManyToManyField(to='productsapp.TechnicalSolutions')),
                ('type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='researchapp.DocumentCategory')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
