# Generated by Django 2.2 on 2019-10-04 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0003_auto_20191004_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='company',
            field=models.ManyToManyField(blank=True, to='authapp.Company'),
        ),
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.ManyToManyField(blank=True, to='researchapp.SubjectOfStudy'),
        ),
    ]
