# Generated by Django 2.2 on 2019-10-04 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0005_auto_20191004_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ и исследование', 'verbose_name_plural': 'Документы и исследования'},
        ),
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'verbose_name': 'Категория документа', 'verbose_name_plural': 'Категории документов'},
        ),
        migrations.AlterModelOptions(
            name='filestorage',
            options={'verbose_name': 'Хранилище файлов', 'verbose_name_plural': 'Хранилище файлов'},
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.ManyToManyField(blank=True, to='researchapp.FileStorage'),
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='автор документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='company',
            field=models.ManyToManyField(blank=True, to='authapp.Company', verbose_name='компания выпустившая документ'),
        ),
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.ManyToManyField(blank=True, to='researchapp.SubjectOfStudy', verbose_name='предмет исседования'),
        ),
        migrations.AlterField(
            model_name='document',
            name='techsol',
            field=models.ManyToManyField(to='productsapp.TechnicalSolutions', verbose_name='техническое решение'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='researchapp.DocumentCategory', verbose_name='категория документа'),
        ),
    ]
