# Generated by Django 2.2 on 2019-10-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0006_auto_20191004_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
    ]
