# Generated by Django 2.2 on 2019-10-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalsolutions',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
        migrations.AlterField(
            model_name='technicalsolutions',
            name='image',
            field=models.ImageField(blank=True, upload_to='аватарка'),
        ),
        migrations.AlterField(
            model_name='technicalsolutions',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлен'),
        ),
    ]
