# Generated by Django 2.2.4 on 2019-10-19 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0001_initial'),
        ('productsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalsolutions',
            name='material_content',
        ),
        migrations.RemoveField(
            model_name='technicalsolutions',
            name='work_content',
        ),
        migrations.AlterField(
            model_name='technicalsolutions',
            name='short_desc',
            field=models.TextField(blank=True, null=True, verbose_name='краткое описание материала'),
        ),
        migrations.CreateModel(
            name='TechnicalSolutionsHasService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicesapp.Service', verbose_name='услуга')),
                ('technicalsolutions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.TechnicalSolutions')),
            ],
        ),
        migrations.CreateModel(
            name='ProductWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='расход материала')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='трудозатраты')),
                ('material', models.ManyToManyField(blank=True, to='productsapp.Material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='productsapp.TechnicalSolutions')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.Work')),
            ],
            options={
                'verbose_name': 'Перечень работ продукта',
                'verbose_name_plural': 'Перечень работ продукта',
            },
        ),
    ]
