# Generated by Django 2.2.4 on 2019-09-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='materialcategory',
            options={'verbose_name': 'Категория материала', 'verbose_name_plural': 'Категории материалов'},
        ),
        migrations.AlterModelOptions(
            name='measuretypes',
            options={'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.AlterModelOptions(
            name='technicalsolutions',
            options={'verbose_name': 'Техническое решение', 'verbose_name_plural': 'Технические решения'},
        ),
    ]
