# Generated by Django 2.2 on 2019-10-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalsolutions',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images'),
        ),
    ]
