# Generated by Django 2.2 on 2019-09-30 06:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='materialcategory',
            options={'verbose_name': 'Категория материала', 'verbose_name_plural': 'Категории материалов'},
        ),
        migrations.AlterModelOptions(
            name='measuretypes',
            options={'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.AlterModelOptions(
            name='technicalsolutions',
            options={'verbose_name': 'Техническое решение', 'verbose_name_plural': 'Технические решения'},
        ),
        migrations.AddField(
            model_name='material',
            name='alt_desc',
            field=models.CharField(blank=True, max_length=128, verbose_name='alt фотографии'),
        ),
        migrations.AddField(
            model_name='material',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='materialcategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialcategory',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='measuretypes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measuretypes',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='technicalsolutions',
            name='alt_desc',
            field=models.CharField(blank=True, max_length=128, verbose_name='alt фотографии'),
        ),
        migrations.AddField(
            model_name='technicalsolutions',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technicalsolutions',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.MaterialCategory', verbose_name='категория материала'),
        ),
        migrations.AlterField(
            model_name='material',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.MeasureTypes', verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='materialcategory',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='категория материала'),
        ),
        migrations.CreateModel(
            name='TechnicalSolutionsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_desc', models.CharField(blank=True, max_length=128, verbose_name='alt фотографии')),
                ('image', models.ImageField(blank=True, upload_to='products_images', verbose_name='Фотография')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='productsapp.TechnicalSolutions')),
            ],
            options={
                'verbose_name': 'Фотография технического решения',
                'verbose_name_plural': 'Фотографии технических решений',
            },
        ),
        migrations.CreateModel(
            name='MaterialImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_desc', models.CharField(blank=True, max_length=128, verbose_name='alt фотографии')),
                ('image', models.ImageField(blank=True, upload_to='products_images', verbose_name='Фотография')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='productsapp.Material')),
            ],
            options={
                'verbose_name': 'Фотография материала',
                'verbose_name_plural': 'Фотографии материалов',
            },
        ),
    ]
