# Generated by Django 2.2 on 2019-10-10 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalsolutions',
            name='measure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productsapp.MeasureTypes', verbose_name='Единица измерения'),
        ),
    ]
