# Generated by Django 2.2 on 2019-10-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0002_auto_20191010_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialimage',
            options={'verbose_name': 'Фотография материалов', 'verbose_name_plural': 'Фотографии материалов'},
        ),
        migrations.AddField(
            model_name='work',
            name='file',
            field=models.FileField(blank=True, upload_to='products_files'),
        ),
    ]
