# Generated by Django 2.2 on 2019-09-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0002_auto_20190930_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='short_desc',
            field=models.CharField(blank=True, max_length=500, verbose_name='краткое описание материала'),
        ),
        migrations.AlterField(
            model_name='technicalsolutions',
            name='short_desc',
            field=models.CharField(blank=True, max_length=500, verbose_name='краткое описание материала'),
        ),
        migrations.AlterField(
            model_name='technicalsolutions',
            name='slug',
            field=models.SlugField(max_length=128, unique=True, verbose_name='слаг'),
        ),
    ]
