# Generated by Django 2.2 on 2019-10-30 13:39

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0002_auto_20191030_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalsolutions',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='products_images'),
        ),
    ]
