# Generated by Django 2.2 on 2019-10-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0002_auto_20191016_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalsolutions',
            name='material_content',
        ),
        migrations.RemoveField(
            model_name='technicalsolutions',
            name='work_content',
        ),
    ]
