# Generated by Django 2.2 on 2019-09-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0003_auto_20190930_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='название материала'),
        ),
    ]
