# Generated by Django 2.2 on 2019-10-16 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0003_auto_20191016_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='трудозатраты')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='productsapp.TechnicalSolutions')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.Work')),
            ],
            options={
                'verbose_name': 'Вид работы',
                'verbose_name_plural': 'Виды работ',
            },
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='расход')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.Material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='productsapp.TechnicalSolutions')),
            ],
            options={
                'verbose_name': 'Материал продукта',
                'verbose_name_plural': 'Материалы продукта',
            },
        ),
    ]
