# Generated by Django 2.2 on 2019-10-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0003_auto_20191010_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='materials',
            field=models.ManyToManyField(blank=True, to='productsapp.Material'),
        ),
    ]
