# Generated by Django 2.2 on 2019-10-10 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0004_work_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.WorkCategory', verbose_name='категория работ'),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='название работ'),
        ),
        migrations.AlterField(
            model_name='workcategory',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='категория работ'),
        ),
    ]
