# Generated by Django 2.2 on 2019-10-17 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0004_productmaterial_productwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwork',
            name='consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='расход материала'),
        ),
        migrations.AddField(
            model_name='productwork',
            name='material',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='productsapp.Material'),
        ),
        migrations.DeleteModel(
            name='ProductMaterial',
        ),
    ]
