# Generated by Django 2.2 on 2019-09-30 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0004_auto_20190930_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=128, unique=True, verbose_name='слаг'),
            preserve_default=False,
        ),
    ]
