# Generated by Django 2.2 on 2019-09-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0005_material_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalsolutions',
            name='short_desc',
        ),
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.SlugField(max_length=500, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='technicalsolutions',
            name='alt_desc',
            field=models.CharField(blank=True, max_length=500, verbose_name='alt фотографии'),
        ),
    ]
