# Generated by Django 2.2.4 on 2019-09-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0005_material_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialimage',
            old_name='name',
            new_name='material',
        ),
    ]
