# Generated by Django 2.2 on 2019-10-17 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0005_auto_20191017_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productwork',
            options={'verbose_name': 'Перечень работ продукта', 'verbose_name_plural': 'Перечень работ продукта'},
        ),
        migrations.AlterField(
            model_name='productwork',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productsapp.Material'),
        ),
    ]
