# Generated by Django 2.2 on 2019-10-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0006_auto_20191017_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productwork',
            name='consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='расход материала'),
        ),
    ]
