# Generated by Django 2.2 on 2019-09-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0006_auto_20190930_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalsolutions',
            name='short_desc',
            field=models.CharField(blank=True, max_length=500, verbose_name='краткое описание материала'),
        ),
    ]
