# Generated by Django 2.2 on 2019-10-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0007_auto_20191017_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productwork',
            name='material',
        ),
        migrations.AddField(
            model_name='productwork',
            name='material',
            field=models.ManyToManyField(blank=True, null=True, to='productsapp.Material'),
        ),
    ]
