# Generated by Django 2.2.4 on 2019-09-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0007_auto_20190929_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialimage',
            name='material',
        ),
    ]
