# Generated by Django 2.2 on 2019-10-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0008_auto_20191017_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productwork',
            name='material',
            field=models.ManyToManyField(blank=True, to='productsapp.Material'),
        ),
    ]
