# Generated by Django 2.2.4 on 2019-09-29 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0009_material_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialimage',
            name='created',
        ),
        migrations.RemoveField(
            model_name='materialimage',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='materialimage',
            name='updated',
        ),
        migrations.AddField(
            model_name='materialimage',
            name='material',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='productsapp.Material'),
        ),
        migrations.AddField(
            model_name='materialimage',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='название фотографии'),
        ),
    ]
