# Generated by Django 2.2 on 2019-10-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0009_auto_20191017_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalsolutions',
            name='short_desc',
            field=models.TextField(blank=True, null=True, verbose_name='краткое описание материала'),
        ),
    ]
