# Generated by Django 2.2.4 on 2019-09-29 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0010_auto_20190929_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialimage',
            name='name',
        ),
        migrations.AddField(
            model_name='materialimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='materialimage',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
