# Generated by Django 2.2 on 2019-10-19 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0001_initial'),
        ('productsapp', '0010_auto_20191017_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSolutionsHasService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicesapp.Service')),
                ('technicalsolutions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.TechnicalSolutions')),
            ],
        ),
    ]
