# Generated by Django 2.2 on 2019-10-20 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0011_technicalsolutionshasservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalsolutionshasservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicesapp.Service', verbose_name='услуга'),
        ),
    ]
