# Generated by Django 2.2 on 2019-10-22 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0012_auto_20191020_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productwork',
            name='material',
            field=models.ManyToManyField(blank=True, to='productsapp.Material', verbose_name='Применяемые материалы'),
        ),
        migrations.AlterField(
            model_name='productwork',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.Work', verbose_name='Вид работы'),
        ),
    ]
