# Generated by Django 2.2.4 on 2019-09-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0012_materialimage_alt_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialimage',
            name='alt_desc',
        ),
    ]
