# Generated by Django 2.2.4 on 2019-09-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0013_remove_materialimage_alt_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialimage',
            name='alt_desc',
            field=models.CharField(blank=True, max_length=128, verbose_name='alt фотографии'),
        ),
    ]
