# Generated by Django 2.2.4 on 2019-09-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0014_materialimage_alt_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='image',
        ),
        migrations.AlterField(
            model_name='materialimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать'),
        ),
    ]
