# Generated by Django 2.2.4 on 2019-09-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0017_material_alt_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.MaterialCategory', verbose_name='категория материала'),
        ),
        migrations.AlterField(
            model_name='material',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapp.MeasureTypes', verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='materialcategory',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='категория материала'),
        ),
        migrations.CreateModel(
            name='TechnicalSolutionsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_desc', models.CharField(blank=True, max_length=128, verbose_name='alt фотографии')),
                ('image', models.ImageField(blank=True, upload_to='products_images', verbose_name='Фотография')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='productsapp.TechnicalSolutions')),
            ],
            options={
                'verbose_name': 'Фотография технического решения',
                'verbose_name_plural': 'Фотографии технических решений',
            },
        ),
    ]
