# Generated by Django 2.2.5 on 2019-10-08 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Категория компании*')),
                ('description', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категорию компании',
                'verbose_name_plural': 'Категории компаний',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Форма компании*')),
                ('description', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Описание формы')),
            ],
            options={
                'verbose_name': 'Форму компании',
                'verbose_name_plural': 'Формы компаний',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='company',
        ),
        migrations.AlterField(
            model_name='users',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(default='не указан', max_length=50, verbose_name='Телефон*'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Логин*'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Полное название*')),
                ('short', models.CharField(blank=True, max_length=30, null=True, verbose_name='Короткое название')),
                ('inn', models.CharField(max_length=30, unique=True, verbose_name='ИНН*')),
                ('city', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Город')),
                ('address', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Эл. почта')),
                ('category', models.ManyToManyField(to='authapp.CategoryCompany', verbose_name='Категория компании*')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authapp.FormCompany', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Новую компанию',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='users',
            name='company',
            field=models.ManyToManyField(to='authapp.Company', verbose_name='Компания'),
        ),
    ]
