# Generated by Django 2.2.4 on 2019-11-05 18:43

import authapp.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='users/avatar/no_avatar.png', upload_to=authapp.models.image_upload_to, verbose_name='Аватар'),
        ),
    ]
