# Generated by Django 2.2.5 on 2019-10-05 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50, unique=True, verbose_name='Категория компании*')),
                ('description', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категорию компании',
                'verbose_name_plural': 'Категории компаний',
                'ordering': ['name_category'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Пользователя', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='company',
        ),
        migrations.AlterField(
            model_name='users',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(default='не указан', max_length=50, verbose_name='Телефон*'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Логин*'),
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(blank=True, max_length=70, null=True, verbose_name='Полное название компании*')),
                ('short_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Короткое название')),
                ('form_company', models.CharField(blank=True, choices=[(None, 'не указано'), ('IP', 'ИП'), ('OOO', 'ООО'), ('OAO', 'ОАО'), ('ZAO', 'ЗАО'), ('PAO', 'ПАО'), ('AO', 'АО'), ('NAO', 'НАО'), ('NKO', 'НКО'), ('ANO', 'АНО')], max_length=3, null=True, verbose_name='Форма')),
                ('inn', models.CharField(max_length=30, unique=True, verbose_name='ИНН*')),
                ('city', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Город')),
                ('address', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Эл. почта')),
                ('category_company', models.ManyToManyField(to='authapp.CategoriesCompanies', verbose_name='Категория компании*')),
            ],
            options={
                'verbose_name': 'Новую компанию',
                'verbose_name_plural': 'Компании',
                'ordering': ['name_company'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authapp.Manufacturer')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='company',
            field=models.ManyToManyField(to='authapp.Companies', verbose_name='Компания'),
        ),
    ]
