# Generated by Django 2.2.4 on 2019-11-03 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyusers',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authapp.Company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='companyusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
