# Generated by Django 2.2.5 on 2019-10-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Пользователя', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_company', verbose_name='логотип'),
        ),
    ]
