# Generated by Django 2.2 on 2019-10-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'не указан'), ('male', 'муж'), ('female', 'жен')], max_length=6, null=True, verbose_name='Пол'),
        ),
    ]
