# Generated by Django 2.2 on 2019-11-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20191103_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, default='users/avatar/no_avatar.png', upload_to='users/avatar', verbose_name='Аватар'),
        ),
    ]
