# Generated by Django 2.2.5 on 2019-10-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20191008_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.BigIntegerField(unique=True, verbose_name='ИНН*'),
        ),
    ]
