# Generated by Django 2.2 on 2019-10-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20191018_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyusers',
            name='works',
            field=models.BooleanField(default=True, verbose_name='Рабоатет в компании'),
        ),
    ]
