# Generated by Django 2.2.5 on 2019-10-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20191008_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.BigIntegerField(max_length=12, unique=True, verbose_name='ИНН*'),
        ),
    ]
