# Generated by Django 2.2 on 2019-10-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20191012_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='company',
            field=models.ManyToManyField(blank=True, to='authapp.Company', verbose_name='Компания'),
        ),
    ]
