# Generated by Django 2.2 on 2019-11-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_users_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='description',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Подробно о себе'),
        ),
    ]
