# Generated by Django 2.2.5 on 2019-10-08 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20191008_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='category',
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='authapp.CategoryCompany', verbose_name='Категория компании*'),
        ),
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.BigIntegerField(unique=True, verbose_name='ИНН*'),
        ),
    ]
