# Generated by Django 2.2 on 2019-10-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20191009_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_company', verbose_name='логотип'),
        ),
    ]
