# Generated by Django 2.2 on 2019-10-12 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20191012_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='city',
        ),
        migrations.RemoveField(
            model_name='users',
            name='company',
        ),
        migrations.RemoveField(
            model_name='users',
            name='position',
        ),
        migrations.RemoveField(
            model_name='users',
            name='project',
        ),
        migrations.CreateModel(
            name='CompanyUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Должность')),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='authapp.Company', verbose_name='Компания')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
        ),
    ]
