# Generated by Django 2.2 on 2019-10-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20191012_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyusers',
            options={'verbose_name': 'Компания - работодатель', 'verbose_name_plural': 'Компании - работодатели'},
        ),
    ]
